[package]
name = "airbus-web"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.7.7", features = ["csr"] }
leptos-use = "0.15.6"
web-sys = "0.3.77"
