[package]
name = "airbus-web"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
console_error_panic_hook = "0.1.7"
leptos = { version = "0.7.7", features = ["csr"] }
web-sys = "0.3.77"
