[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
map-range = "0.1.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
ts-rs = "10.1.0"
wasm-bindgen = "0.2"
